---
- name: Install vim ubuntu
  become: true
  apt:
    state: latest
    name: vim
  when: ansible_distribution == 'Ubuntu'
- name: Install vim osx
  homebrew:
    name: vim
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'
- name: Install vim bundle
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"
- name: Cloning Dots Repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/bigmstone/dots.git"
    dest: "{{ dev_dir }}/dots"
- name: Creating vimrc symlinks
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ dots_dir }}/.vimrc"
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
- name: Install vim dependencies
  become: yes
  become_user: "{{ user }}"
  shell: vim +PluginInstall +qall
  args:
    creates: "{{ home_dir }}/.vim/bundle/ale"
