---
- include_role:
    name: bigmstone.dev
- name: Install st2 system dependencies
  become: true
  apt:
    state: latest
    name:
      - python-pip
      - rabbitmq-server
      - libffi-dev
      - libssl-dev
      - rabbitmq-server
      - python-dev
      - python-setuptools
      - libxslt1-dev
      - libxml2-dev
      - libyaml-dev
      - npm
      - nodejs
      - nginx
  when: ansible_distribution == 'Ubuntu'
- name: Add mongo ppa key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
- name: Add mongo sources list
  become: yes
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb.list
    state=present
    create=yes
- name: Install mongo
  become: yes
  apt:
    name: mongodb-org
    state: latest
    update_cache: yes
- name: Add repos
  become: true
  become_user: "{{ user }}"
  git:
    repo: "git@github.com:StackStorm/{{ item }}.git"
    dest: "{{ dev_dir }}/{{ item }}"
    accept_hostkey: yes
    update: no
  with_items:
    - st2
    - st2web
    - st2-devbox
- name: Add stanley user
  become: true
  user:
    name: stanley
    comment: Stackstorm User
- name: Allow stanley user to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^stanley'
    line: 'stanley ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
