---
- include_role:
    name: bigmstone.dev
- name: Install st2 system dependencies
  become: true
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - mongodb
      - rabbitmq-server
  when: ansible_distribution == 'Ubuntu'
- name: Add stanley user
  become: true
  user:
    name: stanley
    comment: ST2 User
- name: Add repos
  become: true
  become_user: "{{ user }}"
  git:
    repo: "git@github.com:StackStorm/{{ item }}.git"
    dest: "{{ dev_dir }}/{{ item }}"
    accept_hostkey: yes
  with_items:
    - st2
    - st2web
