#!/bin/bash
# ~/.config/eww/scripts/listen-workspaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    case $line in
        workspace*)
            hyprctl activeworkspace -j | jq '.id'
            ;;
        createworkspace*|destroyworkspace*)
            hyprctl workspaces -j | jq 'map({id: .id, windows: .windows}) | sort_by(.id)'
            ;;
        openwindow*|closewindow*)
            hyprctl workspaces -j | jq 'map({id: .id, windows: .windows}) | sort_by(.id)'
            hyprctl activewindow -j | jq -r '.title' | cut -c1-30
            ;;
        activewindow*)
            hyprctl activewindow -j | jq -r '.title' | cut -c1-30
            ;;
    esac
done
