---
- name: Install pyenv dependencies ubuntu
  become: true
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
  when: ansible_distribution == 'Ubuntu'
- name: Download pyenv ubuntu
  get_url:
    url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    dest: /tmp/pyenv-installer
    mode: 0777
  when: ansible_distribution == 'Ubuntu'
- name: Install pyenv ubuntu
  become: yes
  become_user: "{{ user }}"
  shell: /tmp/pyenv-installer
  args:
    creates: "{{ home_dir }}/.pyenv"
  when: ansible_distribution == 'Ubuntu'
- name: Install pyenv osx
  homebrew:
    name: pyenv
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'
- name: Install python versions
  become: yes
  become_user: "{{ user }}"
  shell: "{{ home_dir }}/.pyenv/bin/pyenv install {{ item }}"
  args:
    creates: "{{ home_dir }}/.pyenv/versions/{{ item }}"
  with_items:
    - 2.7.15
    - 3.7.0
- name: Set python versions
  become: yes
  become_user: "{{ user }}"
  shell: "{{ home_dir }}/.pyenv/bin/pyenv global 2.7.15 3.7.0"
  args:
    creates: "{{ home_dir }}/.pyenv/version"
- name: Install pip dependencies
  become: yes
  become_user: "{{ user }}"
  pip:
    name:
      - awscli
      - ipython[all]
    executable: "{{ home_dir }}/.pyenv/versions/2.7.15/bin/pip"   
