---
- name: Cloning Dots Repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/bigmstone/dots.git"
    dest: "{{ dev_dir }}/dots"
- name: Install fish ubuntu
  become: true
  apt:
    state: latest
    name: fish
  when: ansible_distribution == 'Ubuntu'
- name: Install fish mac
  homebrew:
    name: fish
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'
- name: Download omf
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/omf-install
    mode: 0777
- name: Install omf
  become: yes
  become_user: "{{ user }}"
  shell: /tmp/omf-install --noninteractive
  args:
    executable: /usr/bin/fish
    creates: "{{ home_dir }}/.config/omf"
- name: Creates conf.d directory
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ home_dir }}/.config/fish/conf.d"
    state: directory
- name: Adding exports.fish
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ dots_dir }}/exports.fish"
    dest: "{{ home_dir }}/.config/fish/conf.d/exports.fish"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
- name: Install and set clearance theme
  become: yes
  become_user: "{{ user }}"
  shell: "omf install {{ theme }}; omf theme {{ theme }}"
  args:
    executable: /usr/bin/fish
    creates: "{{ home_dir }}/.local/share/omf/themes/{{ theme }}"
