---
- name: Install system dependencies
  become: true
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - mosh
      - virtualbox
      - tmux
      - docker.io
  when: ansible_distribution == 'Ubuntu'
- name: Install vim osx
  homebrew:
    name:
      - mosh
      - tmux
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'
- homebrew_cask:
    name:
      - virtualbox
      - docker
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'
- name: Add user
  become: true
  user:
    name: "{{ user }}"
    comment: "{{ name }}"
    shell: /usr/bin/fish
    groups:
      - sudo
      - docker
    append: yes
- name: Allow user to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ user }}"
    line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: Set authorized key took from file
  become: true
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
- name: Create dev directory
  become: yes
  file:
    path: "{{ dev_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0755
- name: Copy private key
  become: yes
  copy:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    src: ~/.ssh/devbox_ed25519
    dest: "{{ home_dir }}/.ssh/id_ed25519"
- name: Copy public key
  become: yes
  copy:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    src: ~/.ssh/devbox_ed25519.pub
    dest: "{{ home_dir }}/.ssh/id_ed25519.pub"
- name: Setting git name
  become: true
  become_user: "{{ user }}"
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
- name: Setting git email
  become: true
  become_user: "{{ user }}"
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
